if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

export PATH="/usr/local/mysql/bin:$PATH"
export PATH=$PATH:/Users/adam.balsam/\.composer/vendor/drush/drush
export PATH="/usr/local/bin:$PATH"
PATH=$PATH:/usr/local/Cellar/php55/5.5.31/bin
export PATH
